### ISSUE TITLE
[ERROR]

### ISSUE THREAD

**Issue by MeanKid619** [Darkw1nged/Peligon-Plugins#9]
Plugin fails to load.

Load the jar and launch server.
Plugin successfully enables.

[00:19:21 ERROR]: Error occurred while enabling PeligonEconomy v1.1 (Is it up to date?)
java.lang.Error: Connection to database could not be made.
Please notify the developer of this.

at net.peligon.PeligonEconomy.libaries.storage.SQLiteLibary.loadTables(SQLiteLibary.java:45) ~[Peligon-Economy-1.1.jar:?]
at net.peligon.PeligonEconomy.Main.setupStorage(Main.java:156) ~[Peligon-Economy-1.1.jar:?]
at net.peligon.PeligonEconomy.Main.onEnable(Main.java:80) ~[Peligon-Economy-1.1.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596) ~[purpur-1.19.2.jar:git-Purpur-1763]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510) ~[purpur-1.19.2.jar:git-Purpur-1763]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[purpur-1.19.2.jar:git-Purpur-1763]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[purpur-1.19.2.jar:git-Purpur-1763]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1763]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Darkw1nged** [comment]
Hello, Are you using SQLite?

**Comment by Darkw1nged** [comment]
Hello, do you have a subfolder called "data" inside of the PeligonEconoy folder? If not please create it and restart your server.
